### ISSUE TITLE
FR14. Fact Center Tab (Home Page)

### ISSUE THREAD

**Issue by MDrako** [WSU-4110/Quotidiant-App#20]
|FR14.  Fact Center Tab |
|---|
|**Goal**: This will be the main page where the user will most frequently spend their time on Quotitiant. |
|**Stakeholders:** User|
| **Description:** After the user selects topics of interest the fact center is where he will get to see all the facts. There will be a thumbs up or down button to allow for feedback on the source's reliability. There will also be a button to add a fact to your favorites tab and a next fact. |
| **Origin:** First meeting |
| **Version:** 1.0  |
|**Date:** 05/27/2022
|  **Priority:** 1 |

**Comment by MatthewP926** [comment]
Unfortunately we ran out of time before this was completed. Most of the end of is done but we are having issues randomly displaying facts when topics are selected. We have looked into this and would have to redo the way we are outputting code on the homepage. With such little time we aren't able to complete this.
