### ISSUE TITLE
NFR2. Localized application

### ISSUE THREAD

**Issue by KamD23** [WSU-4110/Quotidiant-App#8]
|NFR2.  Localized application|
|---|
|**Goal**: The app shall be able to be localized, allowing the user to change the language based on their preference. |
|**Stakeholders:** User |
| **Description:** Within Quotidiant there will be a setting for the user to change the language of the application to show everything displayed in the language of their selection. |
| **Origin:** Based on the 3rd meeting. |
| **Version:** 1.0  |
|**Date:** 05/28/2022 |
|  **Priority:** 10 |

**Comment by MatthewP926** [comment]
Unable to get to this in settings. Many other things were more important in our non functional enhancements. This app is directed more towards the United States while in development. If we took the app further and expanded to global playstores and iTunes global this would be our first priority.
